### PR TITLE
Used Django's slugify function to generate slugs in course discovery

### PR DESCRIPTION
**Pull request by iam-mhaseeb**
Description: Used Django's slugify function to generate slugs in course discovery service as old slugify algorithm was failing badly on translated strings.

Jira: https://edlyio.atlassian.net/browse/EDLY-1756

Screenshot 2020-08-20 at 1 26 49 PM
Screenshot 2020-08-20 at 1 26 34 PM

### CODE REVIEW

**Review by burhandodhy — APPROVED** [review]
LGTM

**Review by etechdevai — APPROVED** [review]

**Review by zubair-arbi — COMMENTED** [review]
Changes looks good. @iam-mhaseeb Have you verified that the Marketing URL in the course_runs/courses API is unicode?

Please verify that `refresh_course_metadata` command on dev multisite also updates the marketing URL's of the courses.

We also need to update WordPress to use the marketing slug created by the course discovery service.

**Comment by iam-mhaseeb** [comment]
> Changes looks good. @iam-mhaseeb Have you verified that the Marketing URL in the course_runs/courses API is unicode?
> 
> Please verify that `refresh_course_metadata` command on dev multisite also updates the marketing URL's of the courses.
> 
> We also need to update WordPress to use the marketing slug created by the course discovery service.

Yes, verified course_runs API returns the same slug that was generated using title. For WordPress there is a slug field that we would need to update while pulling data from course-discovery.

**Review by ziafazal — APPROVED** [review]
@iam-mhaseeb Wow very simple fix. 👍

**Review by zubair-arbi — APPROVED** [review]
LGTM 👍

**Pull request merged**
